### ISSUE TITLE
训练除yolov3外的cfg文件时，出现AssertionError，加载预训练模型失败

### ISSUE THREAD

**Issue by 1246886181** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#115]
Model Summary: 45 layers, 9.02466e+06 parameters, 9.02466e+06 gradients
Optimizer groups: 16 .bias, 16 Conv2d.weight, 13 other
Traceback (most recent call last):
  File "train.py", line 632, in <module>
    train(hyp)  # train normally
  File "train.py", line 172, in train
    load_darknet_weights(model, weights, pt=opt.pt, FPGA=opt.FPGA)
  File "/home/dell/tongyu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone-master/models.py", line 813, in load_darknet_weights
    assert ptr == len(weights)
AssertionError

**Comment by aHodor-z** [comment]
请问你这个问题解决了吗？

**Comment by 1246886181** [comment]
可以直接不加载模型



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月14日(周三) 晚上6:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone] 训练除yolov3外的cfg文件时，出现AssertionError，加载预训练模型失败 (#115)




 
请问你这个问题解决了吗？

**Comment by aHodor-z** [comment]
请问要如何操作呢？？我还是个小白。。。
