### ISSUE TITLE
NameError: name 'Darknet' is not defined

### ISSUE THREAD

**Issue by MohamedElsaeidy** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#126]
```
python3 normal_prune.py --data data/coco2017.data --weights yolov3_SPP_best.pt --cfg yolov3-spp3.cfg --percent 0.2 
Namespace(batch_size=8, cfg='yolov3-spp3.cfg', data='data/coco2017.data', img_size=416, percent=0.2, weights='yolov3_SPP_best.pt')
Traceback (most recent call last):
  File "normal_prune.py", line 104, in <module>
    model = Darknet(opt.cfg).to(device)
NameError: name 'Darknet' is not defined

trying to prune on yolov3 model but gives this error

**Comment by sharoseali** [comment]
> ```
> python3 normal_prune.py --data data/coco2017.data --weights yolov3_SPP_best.pt --cfg yolov3-spp3.cfg --percent 0.2 
> Namespace(batch_size=8, cfg='yolov3-spp3.cfg', data='data/coco2017.data', img_size=416, percent=0.2, weights='yolov3_SPP_best.pt')
> Traceback (most recent call last):
>   File "normal_prune.py", line 104, in <module>
>     model = Darknet(opt.cfg).to(device)
> NameError: name 'Darknet' is not defined
> 
> trying to prune on yolov3 model but gives this error 
> ```

same happening here.... Any solution ??
