### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by liupeng0606** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#156]
训练期间出现这个问题，前几个epoch正常，然后突然报错了

Traceback (most recent call last):
  File "train.py", line 671, in <module>
    train(hyp)  # train normally
  File "train.py", line 508, in train
    results, maps = test.test(cfg,
  File "/home/liupeng/DET/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone/test.py", line 193, in test
    plot_images(imgs, output_to_target(output, width, height), paths=paths, names=names, fname=f,
  File "/home/liupeng/DET/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone/utils/utils.py", line 1251, in plot_images
    cls = names[cls] if names else cls
IndexError: list index out of range

**Comment by lvy1999s** [comment]
你好，请问你怎么解决这个问题的
