### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by hhhh0** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#19]
0/499      6.3G      2.79     0.299     0.201      3.29         4  1.02e+03: 100%|█| 110/110 [02:37<00:00,  1.43s/it]
Traceback (most recent call last):
  File "train.py", line 497, in <module>
    train(hyp)  # train normally
  File "train.py", line 387, in train
    dataloader=testloader)
  File "D:\2020\prune0513\YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone\test.py", line 74, in test
    _ = model(torch.zeros((1, 3, img_size, img_size), device=device)) if device.type != 'cpu' else None  # run once
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\2020\prune0513\YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone\models.py", line 306, in forward
    return self.forward_once(x)
  File "D:\2020\prune0513\YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone\models.py", line 358, in forward_once
    yolo_out.append(module(x, out))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\2020\prune0513\YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone\models.py", line 279, in forward
    io[..., :2] = torch.sigmoid(io[..., :2]) + self.grid  # xy
RuntimeError: The size of tensor a (32) must match the size of tensor b (20) at non-singleton dimension 3

**Comment by SpursLipu** [comment]
你输入的指令是什么？

**Comment by hhhh0** [comment]
python train.py --data data/coco_1225_ce.data --batch-size 6 -pt --weights weights/yolov3.weights --cfg cfg/yolov3/yolov3.cfg --img-size 512 --epochs 100 --quantized 1 --qlayers 0

**Comment by sadicLiu** [comment]
一样的问题，这是啥原因？

**Comment by sadicLiu** [comment]
@SpursLipu 大佬你这个train.py中test的代码貌似有点问题，我把量化的部分拿到我的yolo代码里能跑起来，用你这个代码跑不起来。另外想请问一下，量化这部分用warmup逐渐降低精度这个策略是咋想到的，绝了。

**Comment by SpursLipu** [comment]
这个问题我最近的更新会解决，大概原因已经找到了，应该是test图片的原尺寸wh非常相近就会报这个错。

**Comment by SpursLipu** [comment]
最新的更新已解决这个问题
