### ISSUE TITLE
加载yolov3.weights出错

### ISSUE THREAD

**Issue by 17868380981** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#45]
Traceback (most recent call last):
  File "F:/Code/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone-master/train.py", line 516, in <module>
    train(hyp)  # train normally
  File "F:/Code/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone-master/train.py", line 151, in train
    load_darknet_weights(model, weights, pt=opt.pt)
  File "F:\Code\YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone-master\models.py", line 566, in load_darknet_weights
    assert ptr == len(weights)
AssertionError

**Comment by 17868380981** [comment]
Traceback (most recent call last):
  File "F:/Code/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone-master/train.py", line 516, in <module>
    train(hyp)  # train normally
  File "F:/Code/YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone-master/train.py", line 151, in train
    load_darknet_weights(model, weights, pt=opt.pt)
  File "F:\Code\YOLOv3-ModelCompression-MultidatasetTraining-Multibackbone-master\models.py", line 502, in load_darknet_weights
    conv_w = torch.from_numpy(weights[ptr:ptr + num_w]).view_as(conv_layer.weight)
RuntimeError: shape '[64, 32, 3, 3]' is invalid for input of size 18203

**Comment by SpursLipu** [comment]
能发一下你使用的指令吗？

**Comment by 17868380981** [comment]
我只换了cfg，其他都是默认的。
另外：双卡训练yolov3-tiny，map是0.65，单卡训练是0.33，数据集dior

**Comment by SpursLipu** [comment]
换了cfg训练如果类别不一样需要使用-pt指令，不然权重大小是不同的。双卡单卡，不是知道是什么情况。

**Comment by ygzhu** [comment]
确实，做量化的时候加载yolov3.weights存在这个问题，但是正常训练的时候就没问题，量化加载之前的pt文件也正常

**Comment by SpursLipu** [comment]
你用的是什么量化方法
