### ISSUE TITLE
能不能使用自己的yolo-mobilenet模型，backbone是mobilenet V2

### ISSUE THREAD

**Issue by wsypy** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#69]
我做完了稀疏化训练，map下降了不少。抱着试试看的态度，进行regular_prune，报了如下错误:
Traceback (most recent call last):
  File "regular_prune.py", line 207, in <module>
    pruned_model = prune_model_keep_size(model, prune_idx, CBL_idx, CBLidx2mask)
  File "/xx/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone-master/utils/prune_utils.py", line 292, in prune_model_keep_size
    update_activation(i, pruned_model, activation, CBL_idx)
  File "/xx/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone-master/utils/prune_utils.py", line 403, in update_activation
    offset = conv_sum.matmul(activation.reshape(-1, 1)).reshape(-1)
RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by SpursLipu** [comment]
这个错和你的结构有关系
