### ISSUE TITLE
谢谢您的付出，我训练yolov4 tiny 出现以下错误 怎么解决呢

### ISSUE THREAD

**Issue by Gaoang112** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#75]
Traceback (most recent call last):
  File "train.py", line 942, in <module>
    train(hyp)  # train normally
  File "train.py", line 161, in train
    load_darknet_weights(model, weights, pt=opt.pt, BN_Fold=opt.BN_Fold, FPGA=opt.FPGA)
  File "/home/ga/YOLOv3v4/models.py", line 699, in load_darknet_weights
    assert ptr == len(weights)
AssertionError

**Comment by shaolingongfuhao** [comment]
在参数里加入-pt应该就可以
