### ISSUE TITLE
多Gpu训练

### ISSUE THREAD

**Issue by chenxyyy** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#97]
Hi ! @SpursLipu    感谢您的无私分享

请问稀疏训练 目前支持多卡训练吗?

**Comment by SpursLipu** [comment]
支持的

**Comment by chenxyyy** [comment]
那如何多卡训练呢？ 我使用了下面的命令，但是报错了

```
python -m torch.distributed.launch --nproc_per_node 2 train.py --data data/coco2017.data --batch-size 40 -pt --weights weights/yolov3-608.weights --cfg cfg/yolov3/yolov3.cfg --devece 2,3 -sr --s 0.0001 --prune 0
```

错误如下：

```
root@e0859732898a:/data/yolo_quan# python -m torch.distributed.launch --nproc_per_node 2 train.py --data data/coco2017.data --batch-size 40 -pt --weights weights/yolov3-608.weights --cfg cfg/yolov3/yolov3.cfg --devece 2,3 -sr --s 0.0001 --prune 0
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex
Apex recommended for faster mixed precision training: https://github.com/NVIDIA/apex
usage: train.py [-h] [--epochs EPOCHS] [--batch-size BATCH_SIZE] [--cfg CFG]
                [--t_cfg T_CFG] [--data DATA] [--multi-scale]
                [--img-size IMG_SIZE [IMG_SIZE ...]] [--rect] [--resume]
                [--nosave] [--notest] [--evolve] [--bucket BUCKET]
                [--cache-images] [--weights WEIGHTS] [--t_weights T_WEIGHTS]
                [--KDstr KDSTR] [--name NAME] [--device DEVICE] [--adam]
                [--ema] [--single-cls] [--sparsity-regularization]
                [--pretrain] [--s S] [--prune PRUNE] [--quantized QUANTIZED]
                [--a-bit A_BIT] [--w-bit W_BIT] [--BN_Fold] [--FPGA]
train.py: error: unrecognized arguments: --local_rank=0 --devece 2,3
usage: train.py [-h] [--epochs EPOCHS] [--batch-size BATCH_SIZE] [--cfg CFG]
                [--t_cfg T_CFG] [--data DATA] [--multi-scale]
                [--img-size IMG_SIZE [IMG_SIZE ...]] [--rect] [--resume]
                [--nosave] [--notest] [--evolve] [--bucket BUCKET]
                [--cache-images] [--weights WEIGHTS] [--t_weights T_WEIGHTS]
                [--KDstr KDSTR] [--name NAME] [--device DEVICE] [--adam]
                [--ema] [--single-cls] [--sparsity-regularization]
                [--pretrain] [--s S] [--prune PRUNE] [--quantized QUANTIZED]
                [--a-bit A_BIT] [--w-bit W_BIT] [--BN_Fold] [--FPGA]
train.py: error: unrecognized arguments: --local_rank=1 --devece 2,3
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-u', 'train.py', '--local_rank=1', '--data', 'data/coco2017.data', '--batch-size', '40', '-pt', '--weights', 'weights/yolov3-608.weights', '--cfg', 'cfg/yolov3/yolov3.cfg', '--devece', '2,3', '-sr', '--s', '0.0001', '--prune', '0']' returned non-zero exit status 2.
```

**Comment by SpursLipu** [comment]
train.py的默认指令就是支持多卡的

**Comment by chenxyyy** [comment]
多谢回复  我找到问题所在了。谢谢啦
